/*
 * @Desc:
 * @Version: v1.00
 * @Author: wc
 * @Date: 2022-11-10 15:29:53
 * @LastEditors: wc
 * @LastEditTime: 2022-11-28 09:29:31
 */
// Generated by 'unplugin-auto-import'
export {}
declare global {}
